### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by y0014984** [platoathens/Reforger-Shop-System#2]
Thank you for your work on this mod. This mod is very useful to create the Arma Reforger experience that we want to. Yesterday (2023-12-04) we played a couple of sessions of our own custom TvT gamemode called "On The Fly". We integrated the Shop System into this gamemode (creating item and vehicle shops on randomly spawned objects) and everything worked very well. Additionally, we want to give you some feedback. Perhaps this will help you and us to create an even better experience.

1. In conjunction with another mod (Lobby Mod) I was not able to use the currency HUD. Some kind of incompatibility. The amount of money never updated in the HUD so I disabled it. To get around the problem I added a custom action to the shop entity that shows a hint with the amount of money in the wallet. That worked well but is not very intuitive. Would be nice if you could instead integrate the currency UI into the shop UI. That's the most important place where I need to know how much money is left. The second most important place would be in the inventory UI.
2. I tried using the "Allow Sale With Full Inventory" option. I expected that the items will then lay on the ground beside the shop. But that was not the case. So I disabled this option for the moment. But it would be nice if this would work as expected.
3. We had to mod your vehicle spawn to solve issues with vehicles spawning in the ground or high in the air if the vehicle spawn point was used in a steep terrain. See this issue: https://github.com/ekudmada/Reforger-Shop-System/issues/1

If some more aspects will come into my mind then I will let you know as a new comment in this issue.

Besides that the shop worked very well. We will continue to use it. Great job. Thank you.

**Comment by y0014984** [comment]
One last note: The automatic description for the UH1H helicopter does not work in the shop, see screenshot.

I think it has to do with your ADM_Utils.GetVehicleUIInfo() method. This line does not seem to work for the heli:

```c#
resultInfo = SCR_EditableVehicleUIInfo.Cast(BaseContainerTools.CreateInstanceFromContainer(baseUIInfo));
```

<img width="388" alt="image" src="https://github.com/ekudmada/Reforger-Shop-System/assets/50139270/1cefcba1-5f02-4234-86c7-0484e28ae481">

**Comment by ekudmada** [comment]
> One last note: The automatic description for the UH1H helicopter does not work in the shop, see screenshot.
> 
> I think it has to do with your ADM_Utils.GetVehicleUIInfo() method. This line does not seem to work for the heli:
> 
> ```cs
> resultInfo = SCR_EditableVehicleUIInfo.Cast(BaseContainerTools.CreateInstanceFromContainer(baseUIInfo));
> ```
> 
> <img alt="image" width="388" src="https://private-user-images.githubusercontent.com/50139270/288340422-1cefcba1-5f02-4234-86c7-0484e28ae481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzA1MjEsIm5iZiI6MTcwNTAzMDIyMSwicGF0aCI6Ii81MDEzOTI3MC8yODgzNDA0MjItMWNlZmNiYTEtNWYwMi00MjM0LTg2YzctMDQ4NGUyOGFlNDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0OGIzOTBlMTZmMTQzODA4MGIwM2VjNWZjMTY0Y2Q5YjRkMmE0ZGI2OGU4OTM1ZjlkMzU1Mjc2MWQ5MzNhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAidhzY9QicdBQcj2nFqi7XeFjmiSv0t9u4MhxPAj_I">

This issue is now fixed and will be in the next update.
