### ISSUE TITLE
Compatibility with v1.2?

### ISSUE THREAD

**Issue by sticks23** [platoathens/Reforger-Shop-System#4]
Hello,

The mod in its current state throws some errors when trying to load up with v1.2.0
![image](https://github.com/ekudmada/Reforger-Shop-System/assets/11834781/18ffe5ab-9170-47be-b5bf-3b45ca4a4b6f)

**Comment by eedson** [comment]
@sticks23  #5 in this pull request I have added a change to allow servers that don't require the BarterTooltip. Waiting for author to accept or modify.

**Comment by ekudmada** [comment]
Updated released for v1.2 compatabiltiy
